<?php

class LDTT_Sample_Data {

    /**
     * Generate a sample course with associated lessons, topics, quizzes, and questions.
     *
     * @param string $course_name The name of the course.
     * @return int The ID of the created course.
     */
    public static function create_sample_course( $course_name = 'Sample Course' ) {
        $course_id = self::create_course( $course_name );

        if ( $course_id ) {
            $lesson_ids = self::create_sample_lessons( $course_id );
            foreach ( $lesson_ids as $lesson_id ) {
                $topic_ids = self::create_sample_topics( $lesson_id );
                $quiz_id = self::create_sample_quiz( $lesson_id );
                if ( $quiz_id ) {
                    self::create_sample_questions( $quiz_id );
                }
            }
        }

        return $course_id;
    }

    /**
     * Create a sample course.
     *
     * @param string $course_name The name of the course.
     * @return int The ID of the created course.
     */
    public static function create_course( $course_name ) {
        $admin_id = LDTT_Helper::get_admin_user_id();

        $course_id = wp_insert_post( array(
            'post_title'   => $course_name,
            'post_type'    => learndash_get_post_type_slug( 'course' ),
            'post_status'  => 'publish',
            'post_content' => 'This is a sample course generated by the LearnDash Testing Toolkit.',
            'post_author'  => $admin_id,
            'meta_input'   => array(
                '_ldtt_test_data' => true,
            ),
        ) );

        if ( ! is_wp_error( $course_id ) ) {
            // Set as free course
            learndash_update_setting( $course_id, 'course_price_type', 'free' );
        }

        return $course_id;
    }

    /**
     * Create sample lessons for a course.
     *
     * @param int $course_id The ID of the course.
     * @return array An array of created lesson IDs.
     */
    public static function create_sample_lessons( $course_id ) {
        $lessons = array();
        $admin_id = LDTT_Helper::get_admin_user_id();

        for ( $i = 1; $i <= 3; $i++ ) {
            $lesson_id = wp_insert_post( array(
                'post_title'   => "Sample Lesson {$i}",
                'post_type'    => learndash_get_post_type_slug( 'lesson' ),
                'post_status'  => 'publish',
                'post_content' => "This is sample lesson {$i} for course ID {$course_id}.",
                'post_author'  => $admin_id,
                'meta_input'   => array(
                    '_ldtt_test_data' => true,
                ),
            ) );

            if ( ! is_wp_error( $lesson_id ) ) {
                // Associate lesson with course
                learndash_update_setting( $lesson_id, 'course', $course_id );
                $lessons[] = $lesson_id;
            }
        }

        return $lessons;
    }

    /**
     * Create sample topics for a lesson.
     *
     * @param int $lesson_id The ID of the lesson.
     * @return array An array of created topic IDs.
     */
    public static function create_sample_topics( $lesson_id ) {
        $topics = array();
        $admin_id = LDTT_Helper::get_admin_user_id();
        $course_id = learndash_get_course_id( $lesson_id );

        for ( $i = 1; $i <= 2; $i++ ) {
            $topic_id = wp_insert_post( array(
                'post_title'   => "Sample Topic {$i}",
                'post_type'    => learndash_get_post_type_slug( 'topic' ),
                'post_status'  => 'publish',
                'post_content' => "This is sample topic {$i} for lesson ID {$lesson_id}.",
                'post_author'  => $admin_id,
                'meta_input'   => array(
                    '_ldtt_test_data' => true,
                ),
            ) );

            if ( ! is_wp_error( $topic_id ) ) {
                // Associate topic with lesson and course
                learndash_update_setting( $topic_id, 'course', $course_id );
                learndash_update_setting( $topic_id, 'lesson', $lesson_id );
                $topics[] = $topic_id;
            }
        }

        return $topics;
    }

    /**
     * Create a sample quiz for a lesson.
     *
     * @param int $lesson_id The ID of the lesson.
     * @return int The ID of the created quiz.
     */
    public static function create_sample_quiz( $lesson_id ) {
        $admin_id = LDTT_Helper::get_admin_user_id();
        $course_id = learndash_get_course_id( $lesson_id );

        $quiz_id = wp_insert_post( array(
            'post_title'   => 'Sample Quiz',
            'post_type'    => learndash_get_post_type_slug( 'quiz' ),
            'post_status'  => 'publish',
            'post_content' => "This is a sample quiz for lesson ID {$lesson_id}.",
            'post_author'  => $admin_id,
            'meta_input'   => array(
                '_ldtt_test_data' => true,
            ),
        ) );

        if ( ! is_wp_error( $quiz_id ) ) {
            // Associate quiz with lesson and course
            learndash_update_setting( $quiz_id, 'course', $course_id );
            learndash_update_setting( $quiz_id, 'lesson', $lesson_id );
        }

        return $quiz_id;
    }

    /**
     * Create sample questions for a quiz.
     *
     * @param int $quiz_id The ID of the quiz.
     */
    public static function create_sample_questions( $quiz_id ) {
        $admin_id = LDTT_Helper::get_admin_user_id();
        $course_id = learndash_get_course_id( $quiz_id );

        for ( $i = 1; $i <= 5; $i++ ) {
            $question_id = wp_insert_post( array(
                'post_title'   => "Sample Question {$i}",
                'post_type'    => learndash_get_post_type_slug( 'question' ),
                'post_status'  => 'publish',
                'post_content' => "This is sample question {$i} for quiz ID {$quiz_id}.",
                'post_author'  => $admin_id,
                'meta_input'   => array(
                    '_ldtt_test_data' => true,
                ),
            ) );

            if ( ! is_wp_error( $question_id ) ) {
                // Associate question with quiz and course
                learndash_update_setting( $question_id, 'quiz', $quiz_id );
                learndash_update_setting( $question_id, 'course', $course_id );
            }
        }
    }
}