<?php

class LDTT_Sample_Data {

    /**
     * Load sample data from JSON file.
     *
     * @return array|null Sample data array or null if file doesn't exist.
     */
    private static function load_sample_data() {
        $file_path = plugin_dir_path( __FILE__ ) . '../../data/learndash-sample-data.json';
        
        if ( ! file_exists( $file_path ) ) {
            return null;
        }
        
        $json_content = file_get_contents( $file_path );
        return json_decode( $json_content, true );
    }

    /**
     * Get random course title from dataset.
     *
     * @return string Random course title.
     */
    public static function get_random_course_title() {
        $data = self::load_sample_data();
        if ( $data && isset( $data['courses']['titles'] ) ) {
            $titles = $data['courses']['titles'];
            return $titles[ array_rand( $titles ) ];
        }
        return 'Sample Course';
    }

    /**
     * Get random course description from dataset.
     *
     * @return string Random course description.
     */
    public static function get_random_course_description() {
        $data = self::load_sample_data();
        if ( $data && isset( $data['courses']['descriptions'] ) ) {
            $descriptions = $data['courses']['descriptions'];
            return $descriptions[ array_rand( $descriptions ) ];
        }
        return 'This is a sample course generated by the LearnDash Testing Toolkit.';
    }

    /**
     * Get random lesson title from dataset.
     *
     * @return string Random lesson title.
     */
    public static function get_random_lesson_title() {
        $data = self::load_sample_data();
        if ( $data && isset( $data['lessons']['titles'] ) ) {
            $titles = $data['lessons']['titles'];
            return $titles[ array_rand( $titles ) ];
        }
        return 'Sample Lesson';
    }

    /**
     * Get random lesson content from dataset.
     *
     * @return string Random lesson content.
     */
    public static function get_random_lesson_content() {
        $data = self::load_sample_data();
        if ( $data && isset( $data['lessons']['content'] ) ) {
            $content = $data['lessons']['content'];
            return $content[ array_rand( $content ) ];
        }
        return 'This is sample lesson content generated by the LearnDash Testing Toolkit.';
    }

    /**
     * Get random topic title from dataset.
     *
     * @return string Random topic title.
     */
    public static function get_random_topic_title() {
        $data = self::load_sample_data();
        if ( $data && isset( $data['topics']['titles'] ) ) {
            $titles = $data['topics']['titles'];
            return $titles[ array_rand( $titles ) ];
        }
        return 'Sample Topic';
    }

    /**
     * Get random topic content from dataset.
     *
     * @return string Random topic content.
     */
    public static function get_random_topic_content() {
        $data = self::load_sample_data();
        if ( $data && isset( $data['topics']['content'] ) ) {
            $content = $data['topics']['content'];
            return $content[ array_rand( $content ) ];
        }
        return 'This is sample topic content generated by the LearnDash Testing Toolkit.';
    }

    /**
     * Get random group title from dataset.
     *
     * @return string Random group title.
     */
    public static function get_random_group_title() {
        $data = self::load_sample_data();
        if ( $data && isset( $data['groups']['titles'] ) ) {
            $titles = $data['groups']['titles'];
            return $titles[ array_rand( $titles ) ];
        }
        return 'Sample Group';
    }

    /**
     * Get random group description from dataset.
     *
     * @return string Random group description.
     */
    public static function get_random_group_description() {
        $data = self::load_sample_data();
        if ( $data && isset( $data['groups']['descriptions'] ) ) {
            $descriptions = $data['groups']['descriptions'];
            return $descriptions[ array_rand( $descriptions ) ];
        }
        return 'This is a sample group generated by the LearnDash Testing Toolkit.';
    }

    /**
     * Generate a sample course with associated lessons, topics, quizzes, and questions.
     *
     * @param string $course_name The name of the course.
     * @return int The ID of the created course.
     */
    public static function create_sample_course( $course_name = null ) {
        // Use random course title if none provided
        if ( empty( $course_name ) ) {
            $course_name = self::get_random_course_title();
        }
        
        $course_id = self::create_course( $course_name );

        if ( $course_id ) {
            $lesson_ids = self::create_sample_lessons( $course_id );
            foreach ( $lesson_ids as $lesson_id ) {
                $topic_ids = self::create_sample_topics( $lesson_id );
                $quiz_id = self::create_sample_quiz( $lesson_id );
                if ( $quiz_id ) {
                    self::create_sample_questions( $quiz_id );
                }
            }
        }

        return $course_id;
    }

    /**
     * Create a sample course.
     *
     * @param string $course_name The name of the course.
     * @return int The ID of the created course.
     */
    public static function create_course( $course_name ) {
        $admin_id = LDTT_Helper::get_admin_user_id();

        $course_id = wp_insert_post( array(
            'post_title'   => $course_name,
            'post_type'    => learndash_get_post_type_slug( 'course' ),
            'post_status'  => 'publish',
            'post_content' => self::get_random_course_description(),
            'post_author'  => $admin_id,
            'meta_input'   => array(
                '_ldtt_test_data' => true,
            ),
        ) );

        if ( ! is_wp_error( $course_id ) ) {
            // Set as free course
            learndash_update_setting( $course_id, 'course_price_type', 'free' );
        }

        return $course_id;
    }

    /**
     * Create sample lessons for a course.
     *
     * @param int $course_id The ID of the course.
     * @return array An array of created lesson IDs.
     */
    public static function create_sample_lessons( $course_id ) {
        $lessons = array();
        $admin_id = LDTT_Helper::get_admin_user_id();

        for ( $i = 1; $i <= 3; $i++ ) {
            $lesson_id = wp_insert_post( array(
                'post_title'   => self::get_random_lesson_title(),
                'post_type'    => learndash_get_post_type_slug( 'lesson' ),
                'post_status'  => 'publish',
                'post_content' => self::get_random_lesson_content(),
                'post_author'  => $admin_id,
                'meta_input'   => array(
                    '_ldtt_test_data' => true,
                ),
            ) );

            if ( ! is_wp_error( $lesson_id ) ) {
                // Associate lesson with course
                learndash_update_setting( $lesson_id, 'course', $course_id );
                $lessons[] = $lesson_id;
            }
        }

        return $lessons;
    }

    /**
     * Create sample topics for a lesson.
     *
     * @param int $lesson_id The ID of the lesson.
     * @return array An array of created topic IDs.
     */
    public static function create_sample_topics( $lesson_id ) {
        $topics = array();
        $admin_id = LDTT_Helper::get_admin_user_id();
        $course_id = learndash_get_course_id( $lesson_id );

        for ( $i = 1; $i <= 2; $i++ ) {
            $topic_id = wp_insert_post( array(
                'post_title'   => self::get_random_topic_title(),
                'post_type'    => learndash_get_post_type_slug( 'topic' ),
                'post_status'  => 'publish',
                'post_content' => self::get_random_topic_content(),
                'post_author'  => $admin_id,
                'meta_input'   => array(
                    '_ldtt_test_data' => true,
                ),
            ) );

            if ( ! is_wp_error( $topic_id ) ) {
                // Associate topic with lesson and course
                learndash_update_setting( $topic_id, 'course', $course_id );
                learndash_update_setting( $topic_id, 'lesson', $lesson_id );
                $topics[] = $topic_id;
            }
        }

        return $topics;
    }

    /**
     * Create a sample quiz for a lesson.
     *
     * @param int $lesson_id The ID of the lesson.
     * @return int The ID of the created quiz.
     */
    public static function create_sample_quiz( $lesson_id ) {
        $admin_id = LDTT_Helper::get_admin_user_id();
        $course_id = learndash_get_course_id( $lesson_id );

        $quiz_id = wp_insert_post( array(
            'post_title'   => 'Sample Quiz',
            'post_type'    => learndash_get_post_type_slug( 'quiz' ),
            'post_status'  => 'publish',
            'post_content' => "This is a sample quiz for lesson ID {$lesson_id}.",
            'post_author'  => $admin_id,
            'meta_input'   => array(
                '_ldtt_test_data' => true,
            ),
        ) );

        if ( ! is_wp_error( $quiz_id ) ) {
            // Associate quiz with lesson and course
            learndash_update_setting( $quiz_id, 'course', $course_id );
            learndash_update_setting( $quiz_id, 'lesson', $lesson_id );
        }

        return $quiz_id;
    }

    /**
     * Create a sample group.
     *
     * @param string $group_name The name of the group.
     * @return int The ID of the created group.
     */
    public static function create_sample_group( $group_name = null ) {
        // Use random group title if none provided
        if ( empty( $group_name ) ) {
            $group_name = self::get_random_group_title();
        }

        $admin_id = LDTT_Helper::get_admin_user_id();

        $group_id = wp_insert_post( array(
            'post_title'   => $group_name,
            'post_type'    => learndash_get_post_type_slug( 'group' ),
            'post_status'  => 'publish',
            'post_content' => self::get_random_group_description(),
            'post_author'  => $admin_id,
            'meta_input'   => array(
                '_ldtt_test_data' => true,
            ),
        ) );

        return $group_id;
    }

    /**
     * Create multiple sample groups.
     *
     * @param int $count Number of groups to create.
     * @return array An array of created group IDs.
     */
    public static function create_sample_groups( $count = 5 ) {
        $groups = array();
        
        for ( $i = 1; $i <= $count; $i++ ) {
            $group_id = self::create_sample_group();
            if ( $group_id && ! is_wp_error( $group_id ) ) {
                $groups[] = $group_id;
            }
        }
        
        return $groups;
    }

    /**
     * Create sample questions for a quiz.
     *
     * @param int $quiz_id The ID of the quiz.
     */
    public static function create_sample_questions( $quiz_id ) {
        $admin_id = LDTT_Helper::get_admin_user_id();
        $course_id = learndash_get_course_id( $quiz_id );

        for ( $i = 1; $i <= 5; $i++ ) {
            $question_id = wp_insert_post( array(
                'post_title'   => "Sample Question {$i}",
                'post_type'    => learndash_get_post_type_slug( 'question' ),
                'post_status'  => 'publish',
                'post_content' => "This is sample question {$i} for quiz ID {$quiz_id}.",
                'post_author'  => $admin_id,
                'meta_input'   => array(
                    '_ldtt_test_data' => true,
                ),
            ) );

            if ( ! is_wp_error( $question_id ) ) {
                // Associate question with quiz and course
                learndash_update_setting( $question_id, 'quiz', $quiz_id );
                learndash_update_setting( $question_id, 'course', $course_id );
            }
        }
    }
}